services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  backend2:
    build:
      context: ./Medifast
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: imoo125
      DB_NAME: medifast
    networks:
      - mynetwork

  frontend:
    build:
      context: ./React2/myapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend2
    networks:
      - mynetwork

  admin_panel:
    build:
      context: ./Admin/admin_panel
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - admin_backend
    networks:
      - mynetwork

  admin_backend:
    build:
      context: ./Admin/admin_backend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: imoo125
      DB_NAME: medifast
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: imoo125
      MYSQL_DATABASE: medifast
    ports:
      - "3306:3306"
    volumes:
      - ./medifast.sql:/docker-entrypoint-initdb.d/medifast.sql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: imoo125
    ports:
      - "8083:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
